<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/12/18 10:27:05
sfConfig::add(array(
  'sf_logging_enabled' => false,
  'sf_logging_level' => 'err',
  'sf_logging_rotate' => true,
  'sf_logging_period' => 7,
  'sf_logging_history' => 10,
  'sf_logging_purge' => false,
));
