<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/12/18 10:27:05

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:root@localhost/database',
), 'propel');
$this->databases['propel'] = $database;
